"""support url for ingestion

Revision ID: d1fd740beee6
Revises: 52e676c7412c
Create Date: 2026-03-05 22:59:03.620784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fd740beee6'
down_revision: Union[str, None] = '52e676c7412c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('ingestion_type', sa.String(length=32), nullable=True))
    op.add_column('source_documents', sa.Column('ingestion_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 'ingestion_url')
    op.drop_column('source_documents', 'ingestion_type')
    # ### end Alembic commands ###
